const $=id=>document.getElementById(id), names={alone:'LLM alone',simple:'Simple stateful',random:'Random reservoir',fly:'Measured fly graph',rewired:'Degree-preserving rewired',fly_reset:'Fly · reset each decision',fly_disconnected:'Fly · output disconnected'};
let state=null,episodes=[],comparing=false,stopCompare=false;
for(const [v,t] of Object.entries(names)){$('condition').add(new Option(t,v))}$('condition').value='fly';
function config(condition=$('condition').value){const overrides={recharge:Number($('recharge').value)};if($('reliabilityA').value!=='')overrides.reliability_a=Number($('reliabilityA').value);if($('reliabilityB').value!=='')overrides.reliability_b=Number($('reliabilityB').value);return {task:$('task').value,condition,seed:Number($('seed').value),interface_seed:Number($('interfaceSeed').value),overrides}}
async function api(path,body){const r=await fetch('/api/'+path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error);return d}
function message(t,error=false){$('status').textContent=t;$('status').className=error?'error':''}
function table(rows,keys){const t=document.createElement('table'),head=t.createTHead().insertRow();keys.forEach(k=>{const th=document.createElement('th');th.textContent=k;head.appendChild(th)});rows.forEach(row=>{const tr=t.insertRow();row.forEach(v=>{tr.insertCell().textContent=v})});return t}

function describeStep(step,task){const box=document.createElement('div'),f=step.frames.at(-1),s=step.signal,o=step.outcome;const intro=document.createElement('p');intro.textContent=task==='resources'?'A and B complete jobs using energy. C restores energy and earns no work credit.':'A and B attempt the same job with uncertain reliability. C inspects the tools. Switching tools costs 0.4.';box.append(intro);const details=task==='resources'?[['Energy before → after',f.energy+' → '+o.energy],['Job A: reward / energy',f.values[0]+' / '+f.costs[0]],['Job B: reward / energy',f.values[1]+' / '+f.costs[1]]]:[['Latest health probe: A / B',f.gauges[0]+' / '+f.gauges[1]],['Probes this interval',step.frames.map(x=>x.gauges.join('/')).join(' → ')]];details.push(['Observed change',step.frames.some(x=>x.changed)?'Yes':'No'],['Controller advice',s.recommendation],['Controller scores A / B / C',s.scores.join(' / ')],['State activity (RMS)',s.state_rms.toFixed(3)],['Controller time',s.controller_ms.toFixed(2)+' ms'],['LLM chose',o.action],['Outcome',o.violation?'Constraint violation':o.failed?'Attempt failed':o.action==='C'?'Recovered / inspected':'Work completed'],['Reward',o.reward.toFixed(2)]);box.append(table(details,['Signal','Value']));return box}

function render(s){state=s;$('metrics').replaceChildren(...[['Decision',s.step+'/6'],['Return',s.summary.return.toFixed(2)],['Energy',s.energy],['Violations',s.summary.violations]].map(([k,v])=>{const d=document.createElement('div');d.className='metric';const b=document.createElement('b');b.textContent=v;const l=document.createElement('span');l.textContent=k;d.append(b,l);return d}));$('steps').replaceChildren();for(const step of s.steps){const tr=document.createElement('tr');[step.outcome.decision+1,step.signal.recommendation,step.outcome.action,step.outcome.reward.toFixed(2),step.latency_s.toFixed(2),step.usage.total_tokens??'?'].forEach(v=>{const td=document.createElement('td');td.textContent=v;tr.appendChild(td)});$('steps').appendChild(tr)}
const last=s.steps.at(-1);if(last){$('observed').replaceChildren(describeStep(last,s.config.task))}else{$('observed').textContent=s.config.task==='tools'?'A and B attempt a job. C inspects reliability. Press Step to see health observations and the local LLM’s first action.':'A and B complete jobs using energy. C restores energy. Press Step to see job values, costs and the local LLM’s first action.'};
if(!comparing)message(s.error|| (s.complete?'Episode complete · Reset to replay':s.busy?'Local LLM is choosing an action…':s.running?'Running · '+names[s.config.condition]:'Ready · '+names[s.config.condition]+' · exploratory session'),!!s.error);
$('run').disabled=s.complete||s.running||comparing;$('step').disabled=s.complete||s.busy||s.running||comparing;$('reset').disabled=s.busy||comparing;$('compare').disabled=s.busy||s.running||comparing}
$('run').onclick=()=>api('run',{}).then(render).catch(e=>message(e.message,true));$('step').onclick=()=>api('step',{}).then(render).catch(e=>message(e.message,true));$('stop').onclick=()=>{stopCompare=true;api('stop',{}).then(render).catch(e=>message(e.message,true))};$('reset').onclick=()=>api('reset',config()).then(render).catch(e=>message(e.message,true));
$('compare').onclick=async()=>{comparing=true;stopCompare=false;$('comparison').hidden=false;$('compareRows').replaceChildren();const rows=[],selectedConfig=config();try{for(const c of Object.keys(names)){if(stopCompare)break;message('Comparing: '+names[c]);await api('reset',{...selectedConfig,condition:c});await api('run',{});let s;do{await new Promise(r=>setTimeout(r,300));s=await api('state');render(s)}while((s.running||s.busy)&&!stopCompare);rows.push([names[c],s.summary.return.toFixed(2),s.summary.progress,s.summary.violations,s.steps.map(x=>x.outcome.action).join(' → ')]);$('compareRows').replaceChildren(table(rows,['Condition','Return','Completed work','Violations','Actions']))}}catch(e){message(e.message,true)}finally{comparing=false;if(state)render(state)}};
function replay(){const r=episodes[Number($('episode').value)];if(!r)return;const i=Number($('replayStep').value)-1,s=r.steps[i];const title=document.createElement('h2');title.textContent=`Decision ${i+1} · ${names[r.condition]} · ${r.task}`;$('replayContent').replaceChildren(title,describeStep(s,r.task));const paired=episodes.filter(x=>x.task===r.task&&x.env_seed===r.env_seed&&x.interface_seed===r.interface_seed);$('paired').replaceChildren(table(paired.map(x=>[names[x.condition],x.summary.return.toFixed(2),x.summary.violations,x.summary.recovery_lag,x.steps.map(s=>s.outcome.action).join(' → ')]),['Condition','Return','Violations','Recovery lag','Actions']))}
$('episode').onchange=replay;$('replayStep').oninput=replay;$('exploreTab').onclick=()=>{$('explore').hidden=false;$('replay').hidden=true;$('exploreTab').className='active';$('replayTab').className=''};$('replayTab').onclick=async()=>{$('explore').hidden=true;$('replay').hidden=false;$('replayTab').className='active';$('exploreTab').className='';try{episodes=(await api('results')).episodes;$('episode').replaceChildren(...episodes.map((r,i)=>new Option(`${r.task} · scenario ${r.env_seed} · interface ${r.interface_seed} · ${names[r.condition]}`,i)));replay()}catch(e){message(e.message,true)}};
setInterval(()=>api('state').then(render).catch(e=>message(e.message,true)),500);api('state').then(render).catch(e=>message(e.message,true));
